imports:
    - { resource: config_dev.yml }

framework:
    error_handler: false
    test: ~

web_profiler:
    toolbar: false
    intercept_redirects: false

zend:
    logger:
        priority: debug

doctrine_phpcr:
    backend:
        url: http://localhost:8080/server/
        workspace: tests
        user: admin
        pass: admin
        transport: