# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

#admin:
#    resource: @SandboxAdminBundle/Resources/config/routing.yml

test:
    pattern:  /hello
    defaults: { _controller: SandboxTestBundle:Test:index }

image_upload:
    pattern: /image/upload/
    defaults: { _controller: sandbox_main.image_controller:uploadAction, _format: json }
    requirements:
        _format: json

image_display:
    pattern: /image/{id}
    defaults: { _controller: sandbox_main.image_controller:displayAction }
    requirements:
        id: '[A-Za-z0-9\.]+'

vie:
    resource: "@LiipVieBundle/Resources/config/routing/phpcr_odm.xml"

vie_asset_management:
    resource: "@LiipVieBundle/Resources/config/routing/asset_search.xml"

cmf:
    resource: @SandboxMainBundle/Resources/config/routing.yml

    # this must come last, its a catch all route
    resource: @SymfonyCmfNavigationBundle/Resources/config/routing.xml
