#admin:
#    resource: @SandboxAdminBundle/Resources/config/routing.yml

cmf:
    resource: @SandboxMainBundle/Resources/config/routing.yml

    # this must come last, its a catch all route
    resource: @SymfonyCmfNavigationBundle/Resources/config/routing.yml
