list:
    pattern: /
    defaults: { _controller: MagazineBundle:Default:listDocument }

set:
    pattern: /set
    defaults: { _controller: MagazineBundle:Default:setDocument }
#    defaults: { _controller: magazine.controller.default::setDocumentAction }

new:
    pattern: /new
    defaults: { _controller: MagazineBundle:Default:newDocument }

show:
    pattern: /show/{path}
    defaults: { _controller: MagazineBundle:Default:showDocument }
    requirements: { path: .* }

remove:
    pattern: /remove/{title}
    defaults: { _controller: MagazineBundle:Default:removeDocument }
    requirements: { title: .* }

set_folder:
    pattern: /folder/set
    defaults: { _controller: MagazineBundle:Default:setFolder }
#    defaults: { _controller: magazine.controller.default::setDocumentAction }

new_folder:
    pattern: /folder/new
    defaults: { _controller: MagazineBundle:Default:newFolder }
