list:
    pattern: /
    defaults: { _controller: MagazineBundle:Default:listDocument }

set:
    pattern: /set
    defaults: { _controller: MagazineBundle:Default:setDocument }
#    defaults: { _controller: magazine.controller.default::setDocumentAction }

new:
    pattern: /new
    defaults: { _controller: MagazineBundle:Default:newDocument }

get:
    pattern: /get/{title}
    defaults: { _controller: MagazineBundle:Default:getDocument }
    requirements: { title: .* }

remove:
    pattern: /remove/{title}
    defaults: { _controller: MagazineBundle:Default:removeDocument }
    requirements: { title: .* }

browse_root:
    pattern: /browse
    defaults: { _controller: MagazineBundle:Default:browse }

browse:
    pattern: /browse/{folder}
    defaults: { _controller: MagazineBundle:Default:browse }
    requirements: { folder: .* }

new_folder:
    pattern: /folder/new/{name}
    defaults: { _controller: MagazineBundle:Default:newFolder }
    requirements: { name: .* }
