services:
    sandbox_main.controller:
        class: Sandbox\MainBundle\Controller\ContentController
        arguments:
            container: "@service_container"
        shared: true

    sandbox_main.image_controller:
        class: Sandbox\MainBundle\Controller\ImageController
        arguments:
            container: "@service_container"
